### ISSUE TITLE
npm ERR! missing script: start

### ISSUE THREAD

**Issue by vladbuk** [acemilyalcin/sample-node-project#6]
After npm install I use npm start and get error:
npm ERR! missing script: start

ubuntu 20.04.5 LTS (Focal Fossa)
node v14.21.0
npm 6.14.17

**Comment by Michael-ozenua090** [comment]
> After npm install I use npm start and get error: npm ERR! missing script: start
> 
> ubuntu 20.04.5 LTS (Focal Fossa) node v14.21.0 npm 6.14.17

got the same error as well

**Comment by acemilyalcin** [comment]
Please make sure package.json at the same path with npm start command which you ran
